### ISSUE TITLE
Regarding the name

### ISSUE THREAD

**Issue by CaspianRoach** [endymonium/NeedToKnow#2]
Could you release a version with the old name on the github please so we don't have to reconfigure all our settings again please? Thanks!

**Comment by endymonium** [comment]
That is not so easy, because the name is hard coded in various places. I added a "how to migrate" ... can you test if that works for you?

**Comment by CaspianRoach** [comment]
I used https://www.bulkrenameutility.co.uk/ to rename the files and Notepad++ to Find and Replace in files. So far it all seems to work fine.

**Comment by CaspianRoach** [comment]
Also regarding the name - the command to hide/show the addon is not very intuitive - i've been tryin to type /tmb because of TiMerBars and been failing every time. /tbs just doesn't sound right

**Comment by endymonium** [comment]
Well nothing easier than that ... /tmb added in 1.2 :)
